---
title: "About the Blog"
description: |
  An introduction to what this blog will cover.
author:
  - name: Nikhil Laxminarayana
    url: https://n1x1l.github.io
date: 2026-05-15
categories:
  - general
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
    code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


## Welcome

This blog serves as a public space for me to document my technical findings and learnings, in an acessible fashion. I hope to be writing on multiple topics, and almost all might turn out to be remotely related to Diffusion Models and Gaussian Splatting, two of the cornerstones of Modern Computer Vision research. Feel free to check this space out for the pieces I write, and I would be glad to get to hear from you. 

With this blog, I hope to share my learnings and key findings with you all and also look forward to learning a lot from you all in the process. Documenting things as I go on has always been a key thing to me, just not out in the public as of yet, which I am hoping to change with this blog. I hope to be regular and update this blog atleast once a month on the 20th day of the month. Feel free to get in touch with me. Cheers! 
